name: CI/CD - Build, Push, and Update ArgoCD Manifests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version
        id: version
        run: echo "tag=$(cat ./VERSION)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mac-portfolio:${{ steps.version.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mac-portfolio:${{ steps.version.outputs.tag }}

  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: oldentomato/localInfra
          ref: main
          token: ${{ secrets.PAT }}

      - name: Update image.tag in values.yaml
        uses: mikefarah/yq@master
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.IMAGE_TAG }}
        with:
          cmd: yq eval -i '.image.tag = env(IMAGE_TAG)' './portfolio/values.yaml'

      - name: Commit manifest changes
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.IMAGE_TAG }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ./portfolio/values.yaml
          git commit -m "ci: update portfolio image tag to $IMAGE_TAG" || echo "No changes to commit"

      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: oldentomato/localInfra
